apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serrano-uvt-ede.fullname" . }}
  labels:
    {{- include "serrano-uvt-ede.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "serrano-uvt-ede.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "serrano-uvt-ede.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serrano-uvt-ede.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or (.Values.containerEnvironmentVariables) (.Values.redis.master) }}
          env:
          {{- end }}
          {{- if .Values.containerEnvironmentVariables }}
          {{- range $key, $val := .Values.containerEnvironmentVariables }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }} 
          {{- if .Values.redis.master }}
            - name: REDIS_END
              value: {{ .Release.Name }}-redis-headless
          {{- end }}
          {{- if .Values.redis.master.containerPorts.redis }}
            - name: REDIS_PORT
              value: {{ .Values.redis.master.containerPorts.redis | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ include "serrano-uvt-ede.fullname" . }}-volume
              subPath: data
              mountPath: /edeservice/data
            - name: {{ include "serrano-uvt-ede.fullname" . }}-volume
              subPath: models
              mountPath: /edeservice/models
            - name: {{ include "serrano-uvt-ede.fullname" . }}-volume
              subPath: service_logs
              mountPath: /edeservice/service/logs
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ include "serrano-uvt-ede.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "serrano-uvt-ede.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
