{{- if .Values.persistence.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "serrano-uvt-ede.fullname" . }}
  labels:
    {{- include "serrano-uvt-ede.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end -}}