replicaCount: 1

image:
  repository: serrano-harbor.rid-intrasoft.eu/serrano/service-assurance-ede
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

containerEnvironmentVariables: {}
#  VARIABLE1: VALUE1
#  VARIABLE2: VALUE2

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5551

persistence:
  enabled: true
  storageClass: "nlsas-01"
  size: 10Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: service-assurance-ede.services.cloud.ict-serrano.eu
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: service-assurance-ede-services-cloud-ict-serrano-eu-tls
      hosts:
        - service-assurance-ede.services.cloud.ict-serrano.eu

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# DO NOT EDIT THE FOLLOWING LINES
redis:
  master:
    count: 1
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false
  auth:
    enabled: false
  serviceAccount:
    create: false
    name: "default"